# Generated by Django 5.0.2 on 2024-04-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='text',
            field=models.CharField(max_length=60),
        ),
    ]
