# Generated by Django 5.0.2 on 2024-04-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comentarios_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
